import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import NavBar from '@/components/navBarr'

import { Nunito_Sans } from 'next/font/google'
import './globals.css'

const nunito = Nunito_Sans({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['300', '600', '800']
})

export const metadata: Metadata = {
  title: 'Where in the world?',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${nunito.variable} font-sans antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
